version: "3.7"
services: 
    # https://mherman.org/blog/dockerizing-a-react-app/
    frontend:
        container_name: microservices-frontend
        build:
          context: frontend
          dockerfile: Dockerfile
        volumes:
          - './frontend:/app'
          - './frontend/node_modules:/app/node_modules'
        ports:
          - 3001:3000
        environment:
          - CHOKIDAR_USEPOLLING=true   

    api-gateway:
        container_name: api-gateway
        image: 'cwarwick/api-gateway'
        ports: 
            - 8080:8080

    shopping-cart-service:
        container_name: shopping-cart-service
        image: 'cwarwick/shopping-cart-service'
    shopping-cart-db:
        container_name: shopping-cart-service-db
        image: 'mongo'
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    user-service:
        container_name: user-service
        image: 'cwarwick/user-service'
    user-db:
        container_name: user-service-db
        image: 'postgres'