version: "3.7"
services: 
    # https://mherman.org/blog/dockerizing-a-react-app/
    frontend:
        container_name: microservices-frontend
        build:
          context: frontend
          dockerfile: Dockerfile
        volumes:
          - './frontend:/app'
          - './frontend/node_modules:/app/node_modules'
        ports:
          - 3001:3000
        environment:
          - CHOKIDAR_USEPOLLING=true   


    api-gateway:
        container_name: api-gateway
        image: 'cwarwick/api-gateway'
        ports: 
            - 8080:8080


    shopping-cart-service:
        build:
          context: shopping-cart-service
          dockerfile: Dockerfile
        command: npm start
        restart: always
        volumes:
          - './backend:/app'
        container_name: shopping-cart-service

    shopping-cart-service-db:
        container_name: shopping-cart-service-db
        image: 'mongo'
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password


    user-service:
        container_name: user-service
        image: 'cwarwick/user-service'

    user-service-db:
        container_name: user-service-db
        image: 'postgres'
        restart: always
        environment: 
            POSTGRES_PASSWORD: password


    inventory-service:
        container_name: inventory-service
        image: 'cwarwick/user-service' #todo: fix this!

    inventory-service-db:
        container_name: inventory-service-db
        image: 'mongo'
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password