version: "3.7"
services: 
    # https://mherman.org/blog/dockerizing-a-react-app/
    frontend:
        container_name: microservices-frontend
        build:
          context: frontend
          dockerfile: Dockerfile
        volumes:
          - './frontend:/app'
          - './frontend/node_modules:/app/node_modules'
        ports:
          - 3001:3000
        environment:
          - CHOKIDAR_USEPOLLING=true   


    api-gateway:
        container_name: api-gateway
        build:
          context: api-gateway
          dockerfile: Dockerfile
        command: npm start
        restart: always
        volumes:
          - './api-gateway:/app'
        ports: 
            - 8080:8080


    shopping-cart-service:
        build:
          context: shopping-cart-service
          dockerfile: Dockerfile
        command: npm start
        restart: always
        volumes:
          - './shopping-cart-service:/app'
        container_name: shopping-cart-service
        ports:
          - 3010:8080

    shopping-cart-service-db:
        container_name: shopping-cart-service-db
        image: 'mongo'
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password


    user-service:
        container_name: user-service
        build:
          context: user-service
          dockerfile: Dockerfile
        command: npm start
        restart: always
        volumes:
          - './user-service:/app'
        ports:
          - 3011:8080

    user-service-db:
        container_name: user-service-db
        image: 'postgres'
        restart: always
        environment: 
            POSTGRES_PASSWORD: password


    inventory-service:
        container_name: inventory-service
        build:
          context: inventory-service
          dockerfile: Dockerfile
        command: npm start
        restart: always
        volumes:
          - './inventory-service:/app'

    inventory-service-db:
        container_name: inventory-service-db
        image: 'postgres'
        restart: always
        environment:
          POSTGRES_PASSWORD: password