http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    host: localhost
    path: /users
  carts:
    host: localhost
    path: /carts
serviceEndpoints:
  users:
    url: 'http://localhost:5020'
  carts:
    url: 'http://localhost:5010'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  users:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: users 
              changeOrigin: true
  carts:
    apiEndpoints:
      - carts
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: carts 
              changeOrigin: true