http:
  port: 8080
  host: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    host: localhost
    paths: /users
  carts:
    host: localhost
    paths: /carts
  inventory:
    host: localhost
    paths: /inventory  
  all:
    host: "*"
    paths: "*"
serviceEndpoints:
  users:
    url: 'http://user-service:8080'
  carts:
    url: 'http://shopping-cart-service:8080'
  inventory:
    url: 'http://inventory-service:8080'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  users:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: users 
              changeOrigin: true
  carts:
    apiEndpoints:
      - carts
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: carts 
              changeOrigin: true
  inventory:
    apiEndpoints:
      - inventory
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: carts 
              changeOrigin: true
  logRequest:
    apiEndpoints:
      - all
    policies:
      - log:
        - action:
            message: "API Endpoint: ${apiEndpoint}, Request: ${JSON.stringify(req.headers)} - baseUrl: ${req.baseUrl} originalUrl: ${req.originalUrl} \n\n Response: ${res.app}"